## downloading data from yfinance

In [1]:
import pandas as pd
import yfinance as yf

In [2]:
ticker = "MSFT"

In [3]:
# downloading the data
data = yf.download(
    ticker,
    start="2015-01-01",
    end="2026-08-27",
    interval="1d",
    auto_adjust=False,
    actions=True
)

[*********************100%***********************]  1 of 1 completed

In [4]:
data.head()

Price,Adj Close,Close,Dividends,High,Low,Open,Stock Splits,Volume
Ticker,MSFT,MSFT,MSFT,MSFT,MSFT,MSFT,MSFT,MSFT
Date,,,,,,,,
2015-01-02,39.607193,46.759998,0.0,47.419998,46.540001,46.660000,0.0,27913900
2015-01-05,39.242950,46.330002,0.0,46.730000,46.250000,46.369999,0.0,39673900
2015-01-06,38.666981,45.650002,0.0,46.750000,45.540001,46.380001,0.0,36447900
2015-01-07,39.158249,46.230000,0.0,46.459999,45.490002,45.980000,0.0,29114100
2015-01-08,40.310215,47.590000,0.0,47.750000,46.720001,46.750000,0.0,29645200

In [5]:
data.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 2929 entries, 2015-01-02 to 2026-08-26
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   (Adj Close, MSFT)     2929 non-null   float64
 1   (Close, MSFT)         2929 non-null   float64
 2   (Dividends, MSFT)     2929 non-null   float64
 3   (High, MSFT)          2929 non-null   float64
 4   (Low, MSFT)           2929 non-null   float64
 5   (Open, MSFT)          2929 non-null   float64
 6   (Stock Splits, MSFT)  2929 non-null   float64
 7   (Volume, MSFT)        2929 non-null   int64
dtypes: float64(7), int64(1)
memory usage: 205.9 KB

In [6]:
data.head()

Price,Adj Close,Close,Dividends,High,Low,Open,Stock Splits,Volume
Ticker,MSFT,MSFT,MSFT,MSFT,MSFT,MSFT,MSFT,MSFT
Date,,,,,,,,
2015-01-02,39.607193,46.759998,0.0,47.419998,46.540001,46.660000,0.0,27913900
2015-01-05,39.242950,46.330002,0.0,46.730000,46.250000,46.369999,0.0,39673900
2015-01-06,38.666981,45.650002,0.0,46.750000,45.540001,46.380001,0.0,36447900
2015-01-07,39.158249,46.230000,0.0,46.459999,45.490002,45.980000,0.0,29114100
2015-01-08,40.310215,47.590000,0.0,47.750000,46.720001,46.750000,0.0,29645200

In [7]:
# flattening
data.columns = data.columns.get_level_values(0)

In [8]:
data.head()

Price,Adj Close,Close,Dividends,High,Low,Open,Stock Splits,Volume
Date,,,,,,,,
2015-01-02,39.607193,46.759998,0.0,47.419998,46.540001,46.660000,0.0,27913900
2015-01-05,39.242950,46.330002,0.0,46.730000,46.250000,46.369999,0.0,39673900
2015-01-06,38.666981,45.650002,0.0,46.750000,45.540001,46.380001,0.0,36447900
2015-01-07,39.158249,46.230000,0.0,46.459999,45.490002,45.980000,0.0,29114100
2015-01-08,40.310215,47.590000,0.0,47.750000,46.720001,46.750000,0.0,29645200

In [9]:
print(data.columns)
print(data.index.name)
print(data.dtypes)

Index(['Adj Close', 'Close', 'Dividends', 'High', 'Low', 'Open',
       'Stock Splits', 'Volume'],
      dtype='str', name='Price')
Date
Price
Adj Close       float64
Close           float64
Dividends       float64
High            float64
Low             float64
Open            float64
Stock Splits    float64
Volume            int64
dtype: object

In [10]:
data.columns.name = None

In [11]:
data.head()

,Adj Close,Close,Dividends,High,Low,Open,Stock Splits,Volume
Date,,,,,,,,
2015-01-02,39.607193,46.759998,0.0,47.419998,46.540001,46.660000,0.0,27913900
2015-01-05,39.242950,46.330002,0.0,46.730000,46.250000,46.369999,0.0,39673900
2015-01-06,38.666981,45.650002,0.0,46.750000,45.540001,46.380001,0.0,36447900
2015-01-07,39.158249,46.230000,0.0,46.459999,45.490002,45.980000,0.0,29114100
2015-01-08,40.310215,47.590000,0.0,47.750000,46.720001,46.750000,0.0,29645200

In [12]:
data = data.reset_index()

In [13]:
data.head()

,Date,Adj Close,Close,Dividends,High,Low,Open,Stock Splits,Volume
0,2015-01-02,39.607193,46.759998,0.0,47.419998,46.540001,46.660000,0.0,27913900
1,2015-01-05,39.242950,46.330002,0.0,46.730000,46.250000,46.369999,0.0,39673900
2,2015-01-06,38.666981,45.650002,0.0,46.750000,45.540001,46.380001,0.0,36447900
3,2015-01-07,39.158249,46.230000,0.0,46.459999,45.490002,45.980000,0.0,29114100
4,2015-01-08,40.310215,47.590000,0.0,47.750000,46.720001,46.750000,0.0,29645200

In [ ]:
# rearranging the data into ohlcv
import pandas as pd

# Remove column-axis name
data.columns.name = None

# Ensure Date is the index name
data.index = pd.to_datetime(data.index)
data.index.name = "Date"

# Put columns in conventional market-data order
data = data[
    [
        "Open",
        "High",
        "Low",
        "Close",
        "Adj Close",
        "Volume",
        "Dividends",
        "Stock Splits"
    ]
]

# Sort chronologically
data = data.sort_index()

# Optional: display prices to 2 decimal places
pd.options.display.float_format = "{:.2f}".format

print(data.head())

In [18]:
data.to_csv("../Data/raw/MSFT.csv")