In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import mplfinance as mpf
from scipy.signal import find_peaks
import yfinance as yf

## data aand data cleaning

In [3]:
ticker = "MSFT"

In [4]:
# downloading the data
data = yf.download(
    ticker,
    start="2015-01-01",
    end="2026-08-27",
    interval="1d",
    auto_adjust=False,
    actions=True
)

[*********************100%***********************]  1 of 1 completed

In [5]:
data.head()

Price,Adj Close,Close,Dividends,High,Low,Open,Stock Splits,Volume
Ticker,MSFT,MSFT,MSFT,MSFT,MSFT,MSFT,MSFT,MSFT
Date,,,,,,,,
2015-01-02,39.607189,46.759998,0.0,47.419998,46.540001,46.660000,0.0,27913900
2015-01-05,39.242958,46.330002,0.0,46.730000,46.250000,46.369999,0.0,39673900
2015-01-06,38.666977,45.650002,0.0,46.750000,45.540001,46.380001,0.0,36447900
2015-01-07,39.158245,46.230000,0.0,46.459999,45.490002,45.980000,0.0,29114100
2015-01-08,40.310219,47.590000,0.0,47.750000,46.720001,46.750000,0.0,29645200

In [6]:
data.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 2929 entries, 2015-01-02 to 2026-08-26
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   (Adj Close, MSFT)     2929 non-null   float64
 1   (Close, MSFT)         2929 non-null   float64
 2   (Dividends, MSFT)     2929 non-null   float64
 3   (High, MSFT)          2929 non-null   float64
 4   (Low, MSFT)           2929 non-null   float64
 5   (Open, MSFT)          2929 non-null   float64
 6   (Stock Splits, MSFT)  2929 non-null   float64
 7   (Volume, MSFT)        2929 non-null   int64
dtypes: float64(7), int64(1)
memory usage: 205.9 KB

In [7]:
data.head()

Price,Adj Close,Close,Dividends,High,Low,Open,Stock Splits,Volume
Ticker,MSFT,MSFT,MSFT,MSFT,MSFT,MSFT,MSFT,MSFT
Date,,,,,,,,
2015-01-02,39.607189,46.759998,0.0,47.419998,46.540001,46.660000,0.0,27913900
2015-01-05,39.242958,46.330002,0.0,46.730000,46.250000,46.369999,0.0,39673900
2015-01-06,38.666977,45.650002,0.0,46.750000,45.540001,46.380001,0.0,36447900
2015-01-07,39.158245,46.230000,0.0,46.459999,45.490002,45.980000,0.0,29114100
2015-01-08,40.310219,47.590000,0.0,47.750000,46.720001,46.750000,0.0,29645200

In [8]:
# flattening
data.columns = data.columns.get_level_values(0)

In [9]:
data.head()

Price,Adj Close,Close,Dividends,High,Low,Open,Stock Splits,Volume
Date,,,,,,,,
2015-01-02,39.607189,46.759998,0.0,47.419998,46.540001,46.660000,0.0,27913900
2015-01-05,39.242958,46.330002,0.0,46.730000,46.250000,46.369999,0.0,39673900
2015-01-06,38.666977,45.650002,0.0,46.750000,45.540001,46.380001,0.0,36447900
2015-01-07,39.158245,46.230000,0.0,46.459999,45.490002,45.980000,0.0,29114100
2015-01-08,40.310219,47.590000,0.0,47.750000,46.720001,46.750000,0.0,29645200

In [10]:
print(data.columns)
print(data.index.name)
print(data.dtypes)

Index(['Adj Close', 'Close', 'Dividends', 'High', 'Low', 'Open',
       'Stock Splits', 'Volume'],
      dtype='str', name='Price')
Date
Price
Adj Close       float64
Close           float64
Dividends       float64
High            float64
Low             float64
Open            float64
Stock Splits    float64
Volume            int64
dtype: object

In [11]:
data.columns.name = None

In [12]:
data.head()

,Adj Close,Close,Dividends,High,Low,Open,Stock Splits,Volume
Date,,,,,,,,
2015-01-02,39.607189,46.759998,0.0,47.419998,46.540001,46.660000,0.0,27913900
2015-01-05,39.242958,46.330002,0.0,46.730000,46.250000,46.369999,0.0,39673900
2015-01-06,38.666977,45.650002,0.0,46.750000,45.540001,46.380001,0.0,36447900
2015-01-07,39.158245,46.230000,0.0,46.459999,45.490002,45.980000,0.0,29114100
2015-01-08,40.310219,47.590000,0.0,47.750000,46.720001,46.750000,0.0,29645200

In [13]:
data = data.reset_index()

In [14]:
data.head()

,Date,Adj Close,Close,Dividends,High,Low,Open,Stock Splits,Volume
0,2015-01-02,39.607189,46.759998,0.0,47.419998,46.540001,46.660000,0.0,27913900
1,2015-01-05,39.242958,46.330002,0.0,46.730000,46.250000,46.369999,0.0,39673900
2,2015-01-06,38.666977,45.650002,0.0,46.750000,45.540001,46.380001,0.0,36447900
3,2015-01-07,39.158245,46.230000,0.0,46.459999,45.490002,45.980000,0.0,29114100
4,2015-01-08,40.310219,47.590000,0.0,47.750000,46.720001,46.750000,0.0,29645200

In [16]:
data.to_csv("../data/raw/MSFT.csv")

In [17]:
# checking for null values or dups
data.isnull().sum()

Date            0
Adj Close       0
Close           0
Dividends       0
High            0
Low             0
Open            0
Stock Splits    0
Volume          0
dtype: int64

In [18]:
data.duplicated().sum()

np.int64(0)

In [19]:
data.head()

,Date,Adj Close,Close,Dividends,High,Low,Open,Stock Splits,Volume
0,2015-01-02,39.607189,46.759998,0.0,47.419998,46.540001,46.660000,0.0,27913900
1,2015-01-05,39.242958,46.330002,0.0,46.730000,46.250000,46.369999,0.0,39673900
2,2015-01-06,38.666977,45.650002,0.0,46.750000,45.540001,46.380001,0.0,36447900
3,2015-01-07,39.158245,46.230000,0.0,46.459999,45.490002,45.980000,0.0,29114100
4,2015-01-08,40.310219,47.590000,0.0,47.750000,46.720001,46.750000,0.0,29645200

## visualization and indicators

In [21]:
print(data.head())

        Date  Adj Close      Close  Dividends       High        Low  \
0 2015-01-02  39.607189  46.759998        0.0  47.419998  46.540001
1 2015-01-05  39.242958  46.330002        0.0  46.730000  46.250000
2 2015-01-06  38.666977  45.650002        0.0  46.750000  45.540001
3 2015-01-07  39.158245  46.230000        0.0  46.459999  45.490002
4 2015-01-08  40.310219  47.590000        0.0  47.750000  46.720001

        Open  Stock Splits    Volume
0  46.660000           0.0  27913900
1  46.369999           0.0  39673900
2  46.380001           0.0  36447900
3  45.980000           0.0  29114100
4  46.750000           0.0  29645200

In [22]:
print(data.dtypes)

Date            datetime64[s]
Adj Close             float64
Close                 float64
Dividends             float64
High                  float64
Low                   float64
Open                  float64
Stock Splits          float64
Volume                  int64
dtype: object

In [23]:
data["Date"] = pd.to_datetime(data["Date"])
data = data.set_index("Date")

In [24]:
print(data.dtypes)

Adj Close       float64
Close           float64
Dividends       float64
High            float64
Low             float64
Open            float64
Stock Splits    float64
Volume            int64
dtype: object

In [25]:
data.head()

,Adj Close,Close,Dividends,High,Low,Open,Stock Splits,Volume
Date,,,,,,,,
2015-01-02,39.607189,46.759998,0.0,47.419998,46.540001,46.660000,0.0,27913900
2015-01-05,39.242958,46.330002,0.0,46.730000,46.250000,46.369999,0.0,39673900
2015-01-06,38.666977,45.650002,0.0,46.750000,45.540001,46.380001,0.0,36447900
2015-01-07,39.158245,46.230000,0.0,46.459999,45.490002,45.980000,0.0,29114100
2015-01-08,40.310219,47.590000,0.0,47.750000,46.720001,46.750000,0.0,29645200

In [26]:
print(data.index.dtype)

datetime64[s]

In [28]:
# market colors
market_colours = mpf.make_marketcolors(
    up = "white",
    down = "black",

    edge = {
        "up": "black",
        "down": "black"
    },

    wick = {
        "up": "black",
        "down": "black"
    },

    volume = {
        "up": "white",
        "down": "black"
    }
)

In [29]:
# chart style
style = mpf.make_mpf_style(
    base_mpf_style = "classic",
    marketcolors = market_colours,
    facecolor = "#D0D0D0",
    figcolor = "#D0D0D0",
    gridcolor = "#A0A0A0",
    gridstyle = "-",
    gridaxis = "both",
    y_on_right = True,
    rc = {
        "axes.labelcolor": "black",
        "xtick.color": "black",
        "ytick.color": "black",
        "font.size": 9
    }
)