# Level One strategies

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot

In [12]:
# data
data = pd.read_csv("../data/cleaned_data/MSFT.csv")
data.head()

         Date        Open        High         Low       Close    Volume
0  2025-09-02  500.470001  506.000000  496.809998  505.119995  18128000
1  2025-09-03  503.790009  507.790009  502.320007  505.350006  16345100
2  2025-09-04  504.299988  508.149994  503.149994  507.970001  15509500
3  2025-09-05  509.070007  511.970001  492.369995  495.000000  31994800
4  2025-09-08  498.109985  501.200012  495.029999  498.200012  16771000

In [13]:
data.head()

         Date        Open        High         Low       Close    Volume
0  2025-09-02  500.470001  506.000000  496.809998  505.119995  18128000
1  2025-09-03  503.790009  507.790009  502.320007  505.350006  16345100
2  2025-09-04  504.299988  508.149994  503.149994  507.970001  15509500
3  2025-09-05  509.070007  511.970001  492.369995  495.000000  31994800
4  2025-09-08  498.109985  501.200012  495.029999  498.200012  16771000

In [14]:
data.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='str')

In [15]:
data.columns.tolist()

['Date', 'Open', 'High', 'Low', 'Close', 'Volume']

In [16]:
data.shape

(271, 6)